import { readFileSync } from 'node:fs';
import { describe, expect, it, vi } from 'vitest';
import { SupabasePurchaseOrderItemRepository, SupabaseSupplierRepository } from '../repositories/supabaseProcurementRepositories';

const migration=readFileSync('supabase/migrations/20260905003000_add_arteflow_multi_tenant_procurement.sql','utf8');

describe('Compras PostgreSQL multi-tenant',()=>{
  it('cria domínio completo tenant-scoped com RLS',()=>{for(const table of ['suppliers','purchase_requests','purchase_request_items','purchase_orders','purchase_order_items','purchase_receipts','purchase_receipt_items','purchase_events'])expect(migration).toContain(`arteflow_${table}`);expect(migration).toContain('enable row level security');expect(migration).toContain("arteflow.procurement.view");});
  it('protege todas as mutações por procurement.manage e auth.uid',()=>{expect(migration).toContain('private.arteflow_require_procurement');expect(migration).toContain("'arteflow.procurement.manage'");expect(migration).toContain('(select auth.uid()) is null');expect(migration).toContain('PROCUREMENT_%_DENIED');});
  it('mantém dinheiro e quantidades em bigint seguro',()=>{expect(migration).toContain('unit_cost_cents bigint');expect(migration).toContain('ordered_quantity_milli bigint');expect(migration).toContain('9007199254740991');expect(migration).not.toMatch(/\b(double precision|real)\b/i);});
  it('numera server-side sem MAX+1',()=>{expect(migration).toContain('arteflow_next_purchase_number');expect(migration).toContain('on conflict(organization_id,prefix,sequence_year) do update');expect(migration).not.toMatch(/max\s*\(/i);});
  it('recebe com lock, idempotência, limite e transação atômica com ledger',()=>{expect(migration).toContain('arteflow_receive_purchase_order');expect(migration).toContain('for update');expect(migration).toContain('ORDER_RECEIPT_EXCEEDS_REMAINING');expect(migration).toContain('unique(organization_id,idempotency_key)');expect(migration).toContain('arteflow_record_inventory_movement');expect(migration).toContain("'RECEIPT'");});
  it('nega escrita direta e execução anônima',()=>{expect(migration).toContain("revoke all on public.%I from public,anon,authenticated");expect(migration).toContain("revoke all on function '");expect(migration).toContain("from public,anon");});
  it('repositório sempre filtra organization_id e recusa save conectado',async()=>{const order=vi.fn().mockResolvedValue({data:[],error:null});let eq:any;eq=vi.fn().mockReturnValue({eq,order});const select=vi.fn().mockReturnValue({eq});const from=vi.fn().mockReturnValue({select});const repo=new SupabaseSupplierRepository({from} as any);await repo.list('org-a');expect(eq.mock.calls[0]).toEqual(['organization_id','org-a']);await expect(repo.save()).rejects.toThrow(/RPC transacional/);});
  it('converte bigint somente quando é inteiro seguro',async()=>{const rows=[{id:'i',organization_id:'o',purchase_order_id:'p',inventory_item_id:'m',material_snapshot:{},ordered_quantity_milli:'9007199254740992',received_quantity_milli:0,unit:'UNIT',unit_cost_cents:1,total_cost_cents:1,created_at:'x',updated_at:'x'}];const order=vi.fn().mockResolvedValue({data:rows,error:null});let eq:any;eq=vi.fn().mockReturnValue({eq,order});const from=vi.fn().mockReturnValue({select:vi.fn().mockReturnValue({eq})});await expect(new SupabasePurchaseOrderItemRepository({from}as any).listAll('o')).rejects.toThrow(/inseguro/);});
});
