import { describe, expect, it, vi } from 'vitest';
import { SupabaseProductionJobRepository, SupabaseProductionEventRepository, SupabaseWorkflowStageRepository } from '../repositories/supabaseProductionRepositories';
import type { ProductionJob } from '../types/domain';

const org='11111111-1111-4111-8111-111111111111';
const jobId='22222222-2222-4222-8222-222222222222';
const baseJob:ProductionJob={id:'local-job',jobCode:'OP-local',organizationId:org,orderId:'33333333-3333-4333-8333-333333333333',orderItemId:'44444444-4444-4444-8444-444444444444',orderNumber:'PED-2026-0001',customer:{id:'c',name:'Cliente Teste'},productName:'Cartaz',quantity:1,unit:'un',finishings:[],stageId:'stage-entry',artworkGate:'NOT_RECEIVED',materialGate:'NOT_CHECKED',financialGate:'PAYMENT_PENDING',priority:'MEDIUM',sector:'Digital',assignee:null,deadlineISO:'2026-09-10T00:00:00.000Z',createdAt:'2026-09-04T00:00:00.000Z',updatedAt:'2026-09-04T00:00:00.000Z',dataOrigin:'user'};

function jobRow(){return{id:jobId,organization_id:org,order_id:baseJob.orderId,order_item_id:baseJob.orderItemId,job_code:'OP-2026-0001',current_stage_id:'stage-entry',artwork_gate:'NOT_RECEIVED',material_gate:'NOT_CHECKED',financial_gate:'PAYMENT_PENDING',priority:'MEDIUM',assigned_user_id:null,assigned_user_name:null,assigned_user_email:null,deadline_at:baseJob.deadlineISO,version:1,created_at:baseJob.createdAt,updated_at:baseJob.updatedAt,arteflow_orders:{order_number:baseJob.orderNumber,customer_snapshot_id:'c',customer_name:'Cliente Teste',customer_document:null,customer_email:null,customer_phone:null,customer_contact_person:null,data_origin:'user'},arteflow_order_items:{product_name:'Cartaz',sector:'Digital',dimension_width:null,dimension_height:null,dimension_unit:null,quantity:1,unit:'un',finishings:[],technical_notes:null,data_origin:'user'}}}

describe('Supabase production repositories',()=>{
  it('cria OP via RPC e recarrega o estado server-side',async()=>{const maybeSingle=vi.fn().mockResolvedValue({data:jobRow(),error:null});const chain:any={select:()=>chain,eq:()=>chain,maybeSingle};const client:any={rpc:vi.fn().mockResolvedValue({data:jobId,error:null}),from:vi.fn(()=>chain)};const repo=new SupabaseProductionJobRepository(client);const result=await repo.saveMany(org,[baseJob]);expect(client.rpc).toHaveBeenCalledWith('arteflow_create_production_job',expect.objectContaining({p_organization_id:org,p_order_item_id:baseJob.orderItemId}));expect(result[0]).toMatchObject({id:jobId,version:1,orderId:baseJob.orderId});});
  it('envia versão esperada ao mover para impedir stale write',async()=>{const maybeSingle=vi.fn().mockResolvedValue({data:{...jobRow(),current_stage_id:'stage-awaiting-file',version:2},error:null});const chain:any={select:()=>chain,eq:()=>chain,maybeSingle};const client:any={rpc:vi.fn().mockResolvedValue({data:jobId,error:null}),from:vi.fn(()=>chain)};const repo=new SupabaseProductionJobRepository(client);const result=await repo.moveAtomic(org,{productionJobId:jobId,targetStageId:'stage-awaiting-file',method:'DRAG_DROP',userId:'ignored',userName:'ignored'},1);expect(client.rpc).toHaveBeenCalledWith('arteflow_move_production_job',expect.objectContaining({p_expected_version:1}));expect(result.version).toBe(2);});
  it('traduz conflito concorrente em erro controlado',async()=>{const client:any={rpc:vi.fn().mockResolvedValue({data:null,error:{message:'PRODUCTION_CONFLICT'}})};const repo=new SupabaseProductionJobRepository(client);await expect(repo.moveAtomic(org,{productionJobId:jobId,targetStageId:'stage-awaiting-file',method:'BUTTON',userId:'x',userName:'x'},1)).rejects.toThrow('outro operador');});
  it('carrega etapas tenant-scoped pela RPC',async()=>{const client:any={rpc:vi.fn().mockResolvedValue({data:[{id:'stage-entry',organization_id:org,name:'Entrada',description:'',sequence:1,color:'#64748b',is_initial:true,is_final:false,is_terminal:false}],error:null})};const rows=await new SupabaseWorkflowStageRepository(client).list(org);expect(rows).toEqual([expect.objectContaining({id:'stage-entry',organizationId:org,isInitial:true})]);});
  it('não permite append arbitrário de histórico conectado',async()=>{const repo=new SupabaseProductionEventRepository({} as any);await expect(repo.append(org,{id:'x',jobId,organizationId:org,eventType:'NOTE_ADDED',description:'x',authorId:'x',authorName:'x',timestamp:new Date().toISOString()})).rejects.toThrow('RPC transacional');});
});
