FROM node:22-alpine AS build

ENV NPM_CONFIG_UPDATE_NOTIFIER=false
ENV NPM_CONFIG_FUND=false

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_ARTEFLOW_MODE
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_PREXYON_PORTAL_URL
ARG VITE_PREXYON_ARTEFLOW_URL
ARG VITE_ARTEFLOW_APP_URL
ARG VITE_PREXYON_ORCAGRAF_URL
ARG VITE_ORCAGRAF_APP_URL
ARG VITE_PREXYON_ARTECHECK_URL
ARG VITE_ARTECHECK_APP_URL

ENV VITE_ARTEFLOW_MODE=$VITE_ARTEFLOW_MODE
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV VITE_PREXYON_PORTAL_URL=$VITE_PREXYON_PORTAL_URL
ENV VITE_PREXYON_ARTEFLOW_URL=$VITE_PREXYON_ARTEFLOW_URL
ENV VITE_ARTEFLOW_APP_URL=$VITE_ARTEFLOW_APP_URL
ENV VITE_PREXYON_ORCAGRAF_URL=$VITE_PREXYON_ORCAGRAF_URL
ENV VITE_ORCAGRAF_APP_URL=$VITE_ORCAGRAF_APP_URL
ENV VITE_PREXYON_ARTECHECK_URL=$VITE_PREXYON_ARTECHECK_URL
ENV VITE_ARTECHECK_APP_URL=$VITE_ARTECHECK_APP_URL

RUN npm run build

FROM caddy:2-alpine

WORKDIR /app

COPY Caddyfile ./
RUN caddy fmt Caddyfile --overwrite

COPY --from=build /app/dist ./dist

CMD ["caddy", "run", "--config", "Caddyfile", "--adapter", "caddyfile"]
