FROM node:22-alpine AS build

ENV NPM_CONFIG_UPDATE_NOTIFIER=false
ENV NPM_CONFIG_FUND=false

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_ARTEFLOW_MODE
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_PREXYON_PORTAL_URL
ARG VITE_ARTEFLOW_APP_URL

ENV VITE_ARTEFLOW_MODE=$VITE_ARTEFLOW_MODE
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_PREXYON_PORTAL_URL=$VITE_PREXYON_PORTAL_URL
ENV VITE_ARTEFLOW_APP_URL=$VITE_ARTEFLOW_APP_URL

RUN npm run build

FROM caddy:2-alpine

WORKDIR /app

COPY Caddyfile ./
RUN caddy fmt Caddyfile --overwrite

COPY --from=build /app/dist ./dist

CMD ["caddy", "run", "--config", "Caddyfile", "--adapter", "caddyfile"]
