import type { SupabaseClient } from '@supabase/supabase-js';
import { ProcurementService, type CreateSupplierInput, type UpdateSupplierInput, type CreatePurchaseRequestInput, type CreatePurchaseOrderInput, type RecordGoodsReceiptInput } from './procurementService';
import type { ISupplierRepository, IPurchaseRequestRepository, IPurchaseRequestItemRepository, IPurchaseOrderRepository, IPurchaseOrderItemRepository, IGoodsReceiptRepository, IGoodsReceiptItemRepository, IProcurementEventRepository, IProcurementSequenceRepository } from '../types/procurementRepository';
import type { IMaterialRepository } from '../types/repository';
import type { InventoryService } from './inventoryService';

const key=()=>globalThis.crypto?.randomUUID?.()??`procurement-${Date.now()}-${Math.random().toString(36).slice(2)}`;
export class SupabaseProcurementService extends ProcurementService {
  constructor(private readonly db:SupabaseClient,private readonly suppliers:ISupplierRepository,private readonly requests:IPurchaseRequestRepository,private readonly requestItems:IPurchaseRequestItemRepository,private readonly orders:IPurchaseOrderRepository,private readonly orderItems:IPurchaseOrderItemRepository,private readonly receipts:IGoodsReceiptRepository,private readonly receiptItems:IGoodsReceiptItemRepository,events:IProcurementEventRepository,sequences:IProcurementSequenceRepository,materials:IMaterialRepository,inventory:InventoryService){super(suppliers,requests,requestItems,orders,orderItems,receipts,receiptItems,events,sequences,materials,inventory);}
  private async rpc(name:string,args:Record<string,unknown>){const{data,error}=await this.db.rpc(name,args);if(error){const known=['PROCUREMENT_MANAGE_DENIED','ORDER_RECEIPT_EXCEEDS_REMAINING','PURCHASE_ORDER_NOT_RECEIVABLE','VERSION_CONFLICT','SUPPLIER_DUPLICATE'];const code=known.find(x=>error.message.includes(x));throw new Error(code??error.message);}return data as string;}
  override async createSupplier(org:string,input:CreateSupplierInput){const id=await this.rpc('arteflow_create_supplier',{p_organization_id:org,p_data:input});const row=await this.suppliers.getById(org,id);if(!row)throw new Error('Fornecedor criado não pôde ser recarregado.');return row;}
  override async updateSupplier(org:string,id:string,input:UpdateSupplierInput){await this.rpc('arteflow_update_supplier',{p_organization_id:org,p_supplier_id:id,p_data:input});const row=await this.suppliers.getById(org,id);if(!row)throw new Error('Fornecedor atualizado não pôde ser recarregado.');return row;}
  override async toggleSupplierActive(org:string,id:string){await this.rpc('arteflow_toggle_supplier',{p_organization_id:org,p_supplier_id:id});const row=await this.suppliers.getById(org,id);if(!row)throw new Error('Fornecedor atualizado não pôde ser recarregado.');return row;}
  override async createPurchaseRequest(org:string,input:CreatePurchaseRequestInput){const id=await this.rpc('arteflow_create_purchase_request',{p_organization_id:org,p_data:input});const request=await this.requests.getById(org,id);if(!request)throw new Error('Solicitação criada não pôde ser recarregada.');return{request,items:await this.requestItems.listByRequestId(org,id)};}
  override async cancelPurchaseRequest(org:string,id:string,reason:string){await this.rpc('arteflow_cancel_purchase_request',{p_organization_id:org,p_request_id:id,p_reason:reason});const row=await this.requests.getById(org,id);if(!row)throw new Error('Solicitação cancelada não pôde ser recarregada.');return row;}
  override async createPurchaseOrder(org:string,input:CreatePurchaseOrderInput){const id=await this.rpc('arteflow_create_purchase_order',{p_organization_id:org,p_data:input});const order=await this.orders.getById(org,id);if(!order)throw new Error('Pedido criado não pôde ser recarregado.');return{order,items:await this.orderItems.listByOrderId(org,id)};}
  override async issuePurchaseOrder(org:string,id:string){await this.rpc('arteflow_issue_purchase_order',{p_organization_id:org,p_order_id:id,p_expected_version:null});const row=await this.orders.getById(org,id);if(!row)throw new Error('Pedido emitido não pôde ser recarregado.');return row;}
  override async cancelPurchaseOrder(org:string,id:string,reason:string){await this.rpc('arteflow_cancel_purchase_order',{p_organization_id:org,p_order_id:id,p_reason:reason,p_expected_version:null});const row=await this.orders.getById(org,id);if(!row)throw new Error('Pedido cancelado não pôde ser recarregado.');return row;}
  override async recordGoodsReceipt(org:string,input:RecordGoodsReceiptInput){const id=await this.rpc('arteflow_receive_purchase_order',{p_organization_id:org,p_order_id:input.purchaseOrderId,p_items:input.items,p_invoice_number:input.invoiceNumber??null,p_notes:input.notes??null,p_idempotency_key:input.idempotencyKey?.trim()||key()});const receipt=await this.receipts.getById(org,id);const order=await this.orders.getById(org,input.purchaseOrderId);if(!receipt||!order)throw new Error('Recebimento não pôde ser recarregado.');return{receipt,order,receiptItems:await this.receiptItems.listByReceiptId(org,id)};}
}
