import type { SupabaseClient } from '@supabase/supabase-js';
import type { Supplier, PurchaseRequest, PurchaseRequestItem, PurchaseOrder, PurchaseOrderItem, GoodsReceipt, GoodsReceiptItem, ProcurementEvent } from '../types/procurement';
import type { ISupplierRepository, IPurchaseRequestRepository, IPurchaseRequestItemRepository, IPurchaseOrderRepository, IPurchaseOrderItemRepository, IGoodsReceiptRepository, IGoodsReceiptItemRepository, IProcurementEventRepository, IProcurementSequenceRepository } from '../types/procurementRepository';

const safe=(v:unknown,f:string)=>{const n=Number(v);if(!Number.isSafeInteger(n))throw new Error(`Valor inseguro recebido em ${f}.`);return n;};
class Base {
  constructor(readonly db:SupabaseClient){}
  protected async rows(table:string,org:string,filters:Record<string,string>={}){let q=this.db.from(table).select('*').eq('organization_id',org);for(const[k,v]of Object.entries(filters))q=q.eq(k,v);const{data,error}=await q.order('created_at');if(error)throw new Error(`Não foi possível carregar Compras: ${error.message}`);return data??[];}
  protected deny():Promise<any>{return Promise.reject(new Error('Compras conectadas só podem ser alteradas por RPC transacional.'));}
}
const supplier=(r:any):Supplier=>({id:r.id,organizationId:r.organization_id,code:r.code,tradeName:r.trade_name,corporateName:r.corporate_name??undefined,document:r.document??undefined,contactName:r.contact_name??undefined,email:r.email??undefined,phone:r.phone??undefined,address:r.address??undefined,defaultLeadTimeDays:r.default_lead_time_days??undefined,paymentTermsSnapshot:r.payment_terms_snapshot??undefined,notes:r.notes??undefined,isActive:r.is_active,dataOrigin:'user',createdAt:r.created_at,updatedAt:r.updated_at});
const request=(r:any):PurchaseRequest=>({id:r.id,organizationId:r.organization_id,requestNumber:r.request_number,status:r.status,source:r.source,productionJobId:r.production_job_id??undefined,jobCode:r.job_code??undefined,notes:r.notes??undefined,cancellationReason:r.cancellation_reason??undefined,requestedBy:r.requested_by,requestedByName:r.requested_by_name,requestedAt:r.requested_at,dataOrigin:'user',createdAt:r.created_at,updatedAt:r.updated_at});
const requestItem=(r:any):PurchaseRequestItem=>({id:r.id,organizationId:r.organization_id,purchaseRequestId:r.purchase_request_id,materialId:r.inventory_item_id,materialSnapshot:{sku:r.material_sku,name:r.material_name,unit:r.material_unit,averageCostCents:safe(r.material_average_cost_cents,'material_average_cost_cents')},requestedQuantityMilli:safe(r.requested_quantity_milli,'requested_quantity_milli'),unit:r.material_unit,reason:r.reason,productionJobId:r.production_job_id??undefined,createdAt:r.created_at});
const order=(r:any):PurchaseOrder=>({id:r.id,organizationId:r.organization_id,orderNumber:r.order_number,supplierId:r.supplier_id,supplierSnapshot:r.supplier_snapshot,status:r.status,expectedAt:r.expected_at??undefined,freightCents:safe(r.freight_cents,'freight_cents'),discountCents:safe(r.discount_cents,'discount_cents'),subtotalCents:safe(r.subtotal_cents,'subtotal_cents'),totalCents:safe(r.total_cents,'total_cents'),notes:r.notes??undefined,cancellationReason:r.cancellation_reason??undefined,issuedAt:r.issued_at??undefined,createdBy:r.created_by,createdByName:r.actor_name,dataOrigin:'user',createdAt:r.created_at,updatedAt:r.updated_at});
const orderItem=(r:any):PurchaseOrderItem=>({id:r.id,organizationId:r.organization_id,purchaseOrderId:r.purchase_order_id,purchaseRequestItemId:r.purchase_request_item_id??undefined,materialId:r.inventory_item_id,materialSnapshot:r.material_snapshot,orderedQuantityMilli:safe(r.ordered_quantity_milli,'ordered_quantity_milli'),receivedQuantityMilli:safe(r.received_quantity_milli,'received_quantity_milli'),unit:r.unit,unitCostCents:safe(r.unit_cost_cents,'unit_cost_cents'),totalCostCents:safe(r.total_cost_cents,'total_cost_cents'),productionJobId:r.production_job_id??undefined,createdAt:r.created_at,updatedAt:r.updated_at});
const receipt=(r:any):GoodsReceipt=>({id:r.id,organizationId:r.organization_id,purchaseOrderId:r.purchase_order_id,receiptNumber:r.receipt_number,supplierSnapshot:r.supplier_snapshot,invoiceNumber:r.invoice_number??undefined,receivedAt:r.received_at,receivedBy:r.received_by,receivedByName:r.received_by_name,notes:r.notes??undefined,idempotencyKey:r.idempotency_key,dataOrigin:'user',createdAt:r.created_at});
const receiptItem=(r:any):GoodsReceiptItem=>({id:r.id,organizationId:r.organization_id,goodsReceiptId:r.purchase_receipt_id,purchaseOrderItemId:r.purchase_order_item_id,materialId:r.inventory_item_id,receivedQuantityMilli:safe(r.received_quantity_milli,'received_quantity_milli'),unitCostCents:safe(r.unit_cost_cents,'unit_cost_cents'),totalCostCents:safe(r.total_cost_cents,'total_cost_cents'),stockMovementId:r.stock_movement_id,createdAt:r.created_at});
const event=(r:any):ProcurementEvent=>({id:r.id,organizationId:r.organization_id,entityType:r.entity_type,entityId:r.entity_id,eventType:r.event_type,description:r.description,metadata:r.metadata??undefined,userId:r.actor_user_id,userName:r.actor_name,createdAt:r.created_at});

export class SupabaseSupplierRepository extends Base implements ISupplierRepository {async list(o:string){return(await this.rows('arteflow_suppliers',o)).map(supplier);}listAll(o:string){return this.list(o);}async getById(o:string,id:string){return(await this.list(o)).find(x=>x.id===id)??null;}async getByCode(o:string,c:string){return(await this.list(o)).find(x=>x.code===c)??null;}async getByDocument(o:string,d:string){return(await this.list(o)).find(x=>x.document===d)??null;}create(){return this.deny();}update(){return this.deny();}deactivate(){return this.deny();}save(){return this.deny();}saveMany(){return this.deny();}}
export class SupabasePurchaseRequestRepository extends Base implements IPurchaseRequestRepository {async listAll(o:string){return(await this.rows('arteflow_purchase_requests',o)).map(request);}async getById(o:string,id:string){return(await this.listAll(o)).find(x=>x.id===id)??null;}async getByRequestNumber(o:string,n:string){return(await this.listAll(o)).find(x=>x.requestNumber===n)??null;}async listByJobId(o:string,id:string){return(await this.listAll(o)).filter(x=>x.productionJobId===id);}save(){return this.deny();}saveMany(){return this.deny();}}
export class SupabasePurchaseRequestItemRepository extends Base implements IPurchaseRequestItemRepository {async listAll(o:string){return(await this.rows('arteflow_purchase_request_items',o)).map(requestItem);}async getById(o:string,id:string){return(await this.listAll(o)).find(x=>x.id===id)??null;}async listByRequest(o:string,id:string){return(await this.rows('arteflow_purchase_request_items',o,{purchase_request_id:id})).map(requestItem);}listByRequestId(o:string,id:string){return this.listByRequest(o,id);}create(){return this.deny();}createMany(){return this.deny();}save(){return this.deny();}saveMany(){return this.deny();}}
export class SupabasePurchaseOrderRepository extends Base implements IPurchaseOrderRepository {async listAll(o:string){return(await this.rows('arteflow_purchase_orders',o)).map(order);}async getById(o:string,id:string){return(await this.listAll(o)).find(x=>x.id===id)??null;}async getByOrderNumber(o:string,n:string){return(await this.listAll(o)).find(x=>x.orderNumber===n)??null;}async listBySupplierId(o:string,id:string){return(await this.listAll(o)).filter(x=>x.supplierId===id);}save(){return this.deny();}saveMany(){return this.deny();}}
export class SupabasePurchaseOrderItemRepository extends Base implements IPurchaseOrderItemRepository {async listAll(o:string){return(await this.rows('arteflow_purchase_order_items',o)).map(orderItem);}async getById(o:string,id:string){return(await this.listAll(o)).find(x=>x.id===id)??null;}async listByOrderId(o:string,id:string){return(await this.rows('arteflow_purchase_order_items',o,{purchase_order_id:id})).map(orderItem);}save(){return this.deny();}saveMany(){return this.deny();}}
export class SupabaseGoodsReceiptRepository extends Base implements IGoodsReceiptRepository {async listAll(o:string){return(await this.rows('arteflow_purchase_receipts',o)).map(receipt);}async getById(o:string,id:string){return(await this.listAll(o)).find(x=>x.id===id)??null;}async getByIdempotencyKey(o:string,k:string){return(await this.listAll(o)).find(x=>x.idempotencyKey===k)??null;}async listByOrderId(o:string,id:string){return(await this.rows('arteflow_purchase_receipts',o,{purchase_order_id:id})).map(receipt);}save(){return this.deny();}saveMany(){return this.deny();}}
export class SupabaseGoodsReceiptItemRepository extends Base implements IGoodsReceiptItemRepository {async listAll(o:string){return(await this.rows('arteflow_purchase_receipt_items',o)).map(receiptItem);}async getById(o:string,id:string){return(await this.listAll(o)).find(x=>x.id===id)??null;}async listByReceiptId(o:string,id:string){return(await this.rows('arteflow_purchase_receipt_items',o,{purchase_receipt_id:id})).map(receiptItem);}save(){return this.deny();}saveMany(){return this.deny();}}
export class SupabaseProcurementEventRepository extends Base implements IProcurementEventRepository {async listAll(o:string){return(await this.rows('arteflow_purchase_events',o)).map(event);}async listByEntity(o:string,t:string,id:string){return(await this.rows('arteflow_purchase_events',o,{entity_type:t,entity_id:id})).map(event);}append(){return this.deny();}appendMany(){return this.deny();}}
export class SupabaseProcurementSequenceRepository implements IProcurementSequenceRepository {getNextSequence():Promise<number>{return Promise.reject(new Error('Numeração de Compras é exclusivamente server-side.'));}setSequence():Promise<void>{return Promise.reject(new Error('Numeração de Compras é exclusivamente server-side.'));}}

export function createSupabaseProcurementRepositories(db:SupabaseClient){return{supplier:new SupabaseSupplierRepository(db),request:new SupabasePurchaseRequestRepository(db),requestItem:new SupabasePurchaseRequestItemRepository(db),order:new SupabasePurchaseOrderRepository(db),orderItem:new SupabasePurchaseOrderItemRepository(db),receipt:new SupabaseGoodsReceiptRepository(db),receiptItem:new SupabaseGoodsReceiptItemRepository(db),event:new SupabaseProcurementEventRepository(db),sequence:new SupabaseProcurementSequenceRepository()};}
