import type { SupabaseClient } from '@supabase/supabase-js';
import type { IReceivablePaymentRepository, IReceivableRepository, ReceivableAccount, ReceivablePayment } from '../types/financial';
const safe=(v:unknown,f:string)=>{const n=Number(v);if(!Number.isSafeInteger(n))throw new Error(`Valor monetário inseguro em ${f}.`);return n;};
const status=(v:string):ReceivableAccount['status']=>({OPEN:'PENDING',PARTIALLY_PAID:'PARTIAL',PAID:'PAID',CANCELED:'CANCELLED'}[v] as ReceivableAccount['status']);
const account=(r:any):ReceivableAccount=>({id:r.id,organizationId:r.organization_id,orderId:r.order_id,orderNumber:r.order_number,customerId:r.customer_id,customerName:r.customer_name,totalCents:safe(r.amount_cents,'amount_cents'),receivedCents:safe(r.paid_amount_cents,'paid_amount_cents'),dueDateISO:r.due_date,status:status(r.status),createdAt:r.created_at,updatedAt:r.updated_at});
const payment=(r:any):ReceivablePayment=>({id:r.id,organizationId:r.organization_id,receivableId:r.receivable_id,amountCents:safe(r.amount_cents,'amount_cents'),paidAt:r.settled_at,method:r.method,notes:r.notes??undefined,idempotencyKey:r.idempotency_key,createdBy:r.created_by,createdByName:r.actor_name,createdAt:r.created_at});
class Base{constructor(public readonly db:SupabaseClient){}protected deny():Promise<any>{return Promise.reject(new Error('Financeiro conectado só pode ser alterado por RPC transacional.'));}}
export class SupabaseReceivableRepository extends Base implements IReceivableRepository{async list(o:string){const{data,error}=await this.db.from('arteflow_financial_receivables').select('*').eq('organization_id',o).order('created_at');if(error)throw new Error(error.message);return(data??[]).map(account);}async getById(o:string,id:string){return(await this.list(o)).find(x=>x.id===id)??null;}async getByOrderId(o:string,id:string){return(await this.list(o)).find(x=>x.orderId===id)??null;}save(){return this.deny();}saveMany(){return this.deny();}}
export class SupabaseReceivablePaymentRepository extends Base implements IReceivablePaymentRepository{async list(o:string){const{data,error}=await this.db.from('arteflow_financial_settlements').select('*').eq('organization_id',o).not('receivable_id','is',null).order('created_at');if(error)throw new Error(error.message);return(data??[]).map(payment);}async listByReceivableId(o:string,id:string){return(await this.list(o)).filter(x=>x.receivableId===id);}async getByIdempotencyKey(o:string,k:string){return(await this.list(o)).find(x=>x.idempotencyKey===k)??null;}save(){return this.deny();}}
export const createSupabaseFinancialRepositories=(db:SupabaseClient)=>({receivable:new SupabaseReceivableRepository(db),payment:new SupabaseReceivablePaymentRepository(db)});
